services:
  grafana:
    build: .
    image: custom-grafana:10.3.1-ubuntu
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
volumes:
  grafana-storage: {}
